import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { toast } from "react-toastify";
import type { Task } from "@/api/taskApi";

interface ExportPDFParams {
  user: {
    name?: string;
    email?: string;
  } | null;
  dailyProgressPercentage: number;
  activeMinutes: number;
  streak: number | null;
  xpStatus: {
    xp: number;
    level: number;
    nextLevelXp: number;
    prevLevelXp: number;
    nextLevelTotal: number;
    progressPercent: number;
  } | null;
  totalTasks: number;
  completedTasks: number;
  visibleTasks: Task[];
  formatMinutesToHourMinute: (minutes: number) => string;
}

export const exportToPDF = ({
  user,
  dailyProgressPercentage,
  activeMinutes,
  streak,
  xpStatus,
  totalTasks,
  completedTasks,
  visibleTasks,
  formatMinutesToHourMinute,
}: ExportPDFParams) => {
  try {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text("Questify - User Activity Report", pageWidth / 2, 20, {
      align: "center",
    });

    // User Info
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`User: ${user?.name || "Unknown"}`, 14, 35);
    doc.text(`Email: ${user?.email || "N/A"}`, 14, 42);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 14, 49);

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 53, pageWidth - 14, 53);

    // Key Performance Indicators
    doc.setFontSize(16);
    doc.setTextColor(40, 40, 40);
    doc.text("Key Performance Indicators", 14, 63);

    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);

    const kpiData = [
      ["Task Completion Rate", `${dailyProgressPercentage}%`],
      ["Active Time", formatMinutesToHourMinute(activeMinutes)],
      ["Current Streak", `${streak || 0} days`],
      ["Current Level", xpStatus ? `Level ${xpStatus.level}` : "Level --"],
      ["Total XP", xpStatus ? `${xpStatus.xp} XP` : "-- XP"],
      [
        "XP to Next Level",
        xpStatus ? `${xpStatus.nextLevelTotal - xpStatus.xp} XP` : "-- XP",
      ],
    ];

    autoTable(doc, {
      startY: 68,
      head: [["Metric", "Value"]],
      body: kpiData,
      theme: "striped",
      headStyles: { fillColor: [255, 201, 74] },
      margin: { left: 14, right: 14 },
    });

    // Task Summary
    const lastTable1 = (doc as any).lastAutoTable;
    let finalY = lastTable1 ? lastTable1.finalY + 10 : 120;

    doc.setFontSize(16);
    doc.setTextColor(40, 40, 40);
    doc.text("Task Summary", 14, finalY);

    finalY += 5;
    const taskData = [
      ["Total Tasks", totalTasks.toString()],
      ["Completed Tasks", completedTasks.toString()],
      ["Pending Tasks", (totalTasks - completedTasks).toString()],
    ];

    autoTable(doc, {
      startY: finalY,
      head: [["Category", "Count"]],
      body: taskData,
      theme: "grid",
      headStyles: { fillColor: [74, 222, 128] },
      margin: { left: 14, right: 14 },
    });

    // Task List (Top 10)
    const lastTable2 = (doc as any).lastAutoTable;
    finalY = lastTable2 ? lastTable2.finalY + 10 : finalY + 50;

    doc.setFontSize(16);
    doc.text("Recent Tasks (Top 10)", 14, finalY);

    finalY += 5;
    const taskListData = visibleTasks
      .slice(0, 10)
      .map((task) => [
        task.title,
        task.status === "completed" ? "Completed" : "Pending",
        `${task.focus_time} min`,
      ]);

    autoTable(doc, {
      startY: finalY,
      head: [["Task Name", "Status", "Focus Time"]],
      body:
        taskListData.length > 0 ? taskListData : [["No tasks yet", "-", "-"]],
      theme: "striped",
      headStyles: { fillColor: [147, 51, 234] },
      margin: { left: 14, right: 14 },
    });

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(
      "Generated by Questify - Your Productivity Companion",
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );

    // Save PDF
    doc.save(`Questify_Report_${new Date().toISOString().split("T")[0]}.pdf`);
    toast.success("Report exported successfully! 📄");
  } catch (error) {
    console.error("Error generating PDF:", error);
    console.error(
      "Error details:",
      error instanceof Error ? error.message : String(error)
    );
    toast.error(
      `Failed to export report: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }
};
